- src/engine/api.rs
- Related to #88 
- Changes `EngineApi` `post` method visibility to private
- Replaces the `ForkChoiceUpdateResponse`, `ExecutionPayloadResponse`, and `PayloadStatusResponse`  structs with the generic `EngineApiResponse` struct
- Ran `cargo clippy` and `cargo test` to verify that everything is working correctly
- Manually ran the project to verify that when the Engine Api errors, the payload is parsed correctly instead of throwing a `serde::error`
> fix: decode errors from engine api

- docker/start-magi.sh
> fix: remove log flags from docker setup

- Makefile
- docker/.env.default
- docker/docker-compose.yml
- docker/start-magi.sh
- docker/start-op-erigon.sh
- docker/start-op-geth.sh
- src/derive/mod.rs
We do a little client diversity.
Doesn't support Base yet but will see if I can get that running next.
> feat: add op-erigon support in docker infra

- src/derive/stages/batcher_transactions.rs
- src/derive/stages/channels.rs
`cargo +nightly clippy --fix --all-features -Z unstable-options`
> chore(clippy): make clippy happy

- src/engine/api.rs
- src/engine/types.rs
> chore: port should be u16

- src/engine/api.rs
set default headers with content-type header
> chore: build client with default content type header

- src/engine/auth.rs
make it harder to accidentally log secret
> chore: dont leak jwt secret in debug impl

- docker/.env.default
- src/derive/mod.rs
Closes #94 
Hopefully my first PR of many, sorry for taking so long, been busy with school :)
Can't run CI, I think there may be an issue at first though with setting the new env variables, but once that is fixed it all should be good
> Moved Test URLs from hardcoded to environment variables

- docker/docker-compose.yml
- src/config/mod.rs
> chore: support base goerli regolith fork

- src/derive/stages/channels.rs
> fix:fix channels remove bug

- bin/network.rs
- src/config/mod.rs
- src/driver/mod.rs
- src/l1/mod.rs
- src/network/handlers/block_handler.rs
> feat: check signatures on unsafe blocks

- docker/start-op-erigon.sh
> chore: removed externalcl flag in op-erigon startup script

- src/driver/types.rs
> fix:fix headinfo test seq num expected

- Cargo.lock
- Cargo.toml
- bin/magi.rs
- docker/.env.default
- docker/docker-compose.yml
- docker/start-op-geth.sh
- src/config/mod.rs
- src/derive/stages/batcher_transactions.rs
- src/derive/stages/batches.rs
- src/driver/engine_driver.rs
- src/driver/mod.rs
- src/engine/api.rs
- src/l1/mod.rs
- Added mainnet configs
- Added better timeout logic for engine api
- Increased cached unsafe blocks size
> feat: optimism mainnet support

- Cargo.lock
- bin/magi.rs
- docker/start-op-geth.sh
- src/config/mod.rs
- src/driver/mod.rs
- src/network/service/discovery.rs
- src/runner/mod.rs
all your base are belong to you.
> feat: support base mainnet

- Cargo.lock
- src/derive/stages/batcher_transactions.rs
> fix: constrain is_last frame byte to 0 or 1

- bin/magi.rs
- src/config/mod.rs
- src/derive/stages/attributes.rs
> feat:add base-sepolia config

- src/derive/stages/batches.rs
> Fix batch derivation semantics related to sequencing window

- Cargo.lock
- Cargo.toml
- src/rpc/mod.rs
Ports ethers types and providers to alloy.
**Metadata**
Fixes #235
> chore(rpc): Port Rpc Types and Providers to Alloy

- Cargo.lock
- Cargo.toml
- src/engine/fork.rs
- src/engine/payload.rs
- src/rpc/mod.rs
- src/runner/mod.rs
> [!NOTE]
> Merge **after** #237 to keep a clean history.
Ports ethers types and providers to alloy.
**Metadata**
Fixes #236
> chore(runner): Migrate to Alloy Types

- .github/workflows/publish-docker.yml
> feat: enable docker-push on merge to master
