a16z/magi

docs/architecture.md, src/config/mod.rs, src/derive/stages/batches.rs, src/driver/engine_driver.rs
As specified in #84, adds the network blocktime as a config value and replaces all blocktime-related uses of `2` (the default value) with the configured blocktime. Also ran `cargo clippy/fmt/test` to make sure all's good on that front!
Closes #84
=> feat: use configured blocktime instead of hardcoded values

src/derive/stages/batcher_transactions.rs
Use `VecDeque` for storing batcher transactions as it is more [performant](https://doc.rust-lang.org/stable/std/collections/struct.VecDeque.html) for handling FIFO queues than `Vec` because of non contiguous memory layout
=> perf: `VecDeque` for fifo queue

src/derive/mod.rs
It seems to me like the intention was for the method to be similar to [`Peekable`](https://doc.rust-lang.org/stable/std/iter/struct.Peekable.html)
=> fix: `peek` method typo

src/derive/mod.rs, src/derive/purgeable.rs, src/derive/stages/attributes.rs, src/derive/stages/batcher_transactions.rs, src/derive/stages/batches.rs, src/derive/stages/channels.rs
Pipeline mutexes no more! Closes #83 
This PR refactors stages into wrapping iterators over each other.
The pipeline pushes the transactions to first stage using mpsc channel.
The purge is cascading where each stage calls purge on the previous.
=> refactor: pipeline

Cargo.lock, Cargo.toml, bin/magi.rs, docker/start-magi.sh, src/telemetry/logging.rs
Added the ability to configure logging to a directory. 
Closes #85 
---
The implementation uses `tracing-appender` which plays quite well with the current tracing setup and provides a non-blocking subscriber for writing to files.
Features:
- new `cli.logs_dir` field to specify where to place logs. If `None` is provided, logging will only be done on stdout.
- new `cli.logs_rotation` field can also be specified to rotate log files every time period. If `None` is provided, the rotation policy is set to `never`.
I updated Magi's startup script with the new CLI fields, however I am not 100% sure of the locations specified for logs. Is `$DATADIR/logs` going to be fine?
=> Feat: store debug logs in files

src/telemetry/metrics.rs
1. Changed the return type of the init function to eyre::Result<()> to enable better error handling and reporting.
2. Changed the call to start using the ? operator to propagate any errors that may occur when starting the Prometheus Exporter.
3. Added more detailed error messages using the WrapErr method to provide additional context about possible errors.
=> Improve error handling in telemetry initialization

Cargo.lock, Cargo.toml, src/l1/mod.rs
Avoid rehashing of event signatures in the chain watcher.
Used `once_cell` instead of existing `lazy_static` dep, because it's [making its way to std](https://github.com/rust-lang/rust/pull/105587). Happy to swap existing static metrics to `once_cell` as well in a follow-up PR, when this one is merged.
=> perf(l1): avoid event topic rehashing

Cargo.lock, Cargo.toml, docker/docker-compose.yml, src/config/mod.rs, src/driver/mod.rs, src/lib.rs, src/rpc/mod.rs
- Added RPC to get latest output root at block
TODO
Request
```
{
"jsonrpc": "2.0",
"method": "optimism_outputAtBlock",
"params": [4074155],
"id": 1
}
```
Response
```
{
"jsonrpc": "2.0",
"result": {
"outputRoot": "0xd644fd2ec6bd24785902a47f16b243af1a08db9c8fd8d148278b7177712858e6",
"version": "0x0000000000000000000000000000000000000000000000000000000000000000",
"stateRoot": "0x762473ad22b64cd68f4704b2af32b88ca32b81b324713ef6773556ff8bb4674e",
"withdrawalStorageRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421"
},
"id": 1
}
```
Error handling, unit tests coming in subsequent PR.
Fixes #86
=> feat(rpc): add rpc call to query output at block

src/driver/engine_driver.rs
Using tokio spawn for the forkchoice update meant that it was possible to attempt to build the next payload before the forkchoice update took effect on the execution engine. If this happens for an unsafe block, when we try to apply the same block as a safe block, we will end up not skipping that update, and attempt to build a payload on the wrong parent which will fail.
=> fix: forkchoice update race condition

src/common/mod.rs, src/derive/mod.rs, src/derive/stages/attributes.rs, src/driver/engine_driver.rs, src/driver/mod.rs, src/driver/types.rs
This is useful when a datadir (such as the one that op-erigon team ships) is snapshotted not on an epoch boundary. This will also let us finalize blocks that are not on an epoch boundary with only a few more modifications. Will address that in a follow up PR.
=> feat: support startup on non epoch boundary

Cargo.lock, Cargo.toml
We can switch to the released version of Ethers :)
=> chore: update ethers version to 2.0.6

bin/magi.rs, src/config/mod.rs, src/driver/mod.rs, src/l1/mod.rs
Closes #150 
Adds support for reading external chain info. It works by simply specifying a file in the `network` flag when running magi.
Example:
```
exec magi \
--network "./rollup.json" \
--jwt-secret [...]
```
- fixed a typo across the repo: `unsafe_block_singer`
- added the `l1_chain_id` field to the `ChainConfig` struct, as I think it could be useful and it's usually included in the devnet rollup config
- added the `ExternalChainConfig` struct to make it possible to use external JSON configs. A test has been added which showcases the result of such parsing, with a standard `rollup.json` file created by `op-node`'s devnet command.
- the L1 start epoch's timestamp is set to 0 because this information is missing in the rollup.json file. If this will be a problem, we will need to add it …
=> Feat/add support for external chains via JSON

Cargo.toml, Dockerfile, docker/start-op-geth.sh
Currently, the image is being built using the `rust:latest` base image, which is based on `debian:bullseye`, where:
```
ldd --version
ldd (Debian GLIBC 2.31-13+deb11u6) 2.31
```
Then, the final binary is placed in the `debian:buster` image, where version is:
```
ldd --version
ldd (Debian GLIBC 2.28-10+deb10u2) 2.28
```
This leads to an error during application startup, due to a missing `GLIBC_2.29` version, as shown below:
```
magi: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by magi)
```
To resolve this issue and ensure library compatibility, it's recommended to use the same Debian version for both images. In this case, it's proposed to switch from `debian:buster-slim` to `debian:bullseye-slim`.
```diff
-FROM debian:buster-slim
+FROM debian:bullseye-slim
=> Update Debian Version to Resolve GLIBC Compatibility Issue

Cargo.lock, Cargo.toml, src/driver/info.rs, src/driver/mod.rs, src/driver/types.rs
Refactors out the `HeadInfo` fetching from inside the `Driver`'s `from_config` method.
This allows us to unit test head info fetching by wrapping the provider in a minimal trait.
=> feat(driver): Graceful HeadInfo Fetching

src/derive/mod.rs, src/l1/mod.rs
Hey,
Using `std::sync::mpsc::sync_channel` inside `tokio::spawn` can lead to the blocking of the runtime. Since the channel is bounded to 1,000 messages, the runtime might block if the channel becomes full. This behavior can be observed, for instance, when the L1 node is hosted on the same machine and blocks processing fast. We noticed this issue with our local OP devnet setup.
By replacing `sync_channel` with `tokio::sync::mpsc::channel`, we can circumvent this issue. If the channel becomes full using the latter, it won't block the runtime.
=> fix(l1): Use tokio `mpsc::channel` instead of std `sync_channel` in L1 watcher

Dockerfile
We have once again encountered an issue with glibc on arch64:
```
magi: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by magi)
magi  | magi: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by magi)
magi  | magi: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by magi)
magi  | magi: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by magi)
magi  | magi: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by magi)
```
As you can see, the versions differ again between the `rust:latest` image and `debian:bullseye-slim`: 
rust:latest
```
root@aed8602b702f:/# ldd --version
ldd (Debian GLIBC 2.36-9+deb12u1) 2.36
```
debian:bullseye-slim
```
root@76e82549a3bc:/# ldd …
```
=> [docker] Fix glibc problem

bin/magi.rs, docker/.env.default, docker/start-op-geth.sh, src/config/mod.rs, src/derive/state.rs, src/driver/mod.rs
Hey team,
We've introduced support for the Sepolia network along with the necessary configurations. Additionally, we've implemented several fixes and updates as outlined in [Issue #166](https://github.com/a16z/magi/issues/166).
Specifically, we've removed the `state.is_full` check. Now, we update the state once the attributes are processed. Without this change, the system was entering an infinite loop, producing blocks with identical timestamps and data. These were subsequently rejected by `op-eth`. Referring to the following section for context:
https://github.com/a16z/magi/blob/36e3e07b46822c0354e5a3d94beb97c522980e02/src/derive/stages/batches.rs#L104-L138
=> feat: Sepolia support

.dockerignore
There's no need to copy the `.git`/`.github` directories or the `.gitignore` for the Docker build.
=> chore(docker): ignore Git files

bin/magi.rs
Adds a `jwt_file` field to the cli.
This allows users to specify a file containing the jwt token hex string via the `--jwt-file` flag as an alternative to passing the token hex string to the `--jwt-secret` flag.
Allows for magi to work more seamlessly with trusted nodes by sharing the jwt token file.
=> feat: JWT Secret PathBuf

src/driver/types.rs, src/l1/mod.rs
Clippy introduces the [`get_first` rule](https://rust-lang.github.io/rust-clippy/master/index.html#/get_first) which prefers `first()` instead of `first(0)`. In recent nightly toolchain updates, the `clippy` action [fails](https://github.com/SpecularL2/magi/actions/runs/6607922576/job/17980361805) because of the above rule.
In this pr, both places, where attribute deposit transaction is obtained from the transaction list, are changed from `transactions.get(0)` to `transaction.first()`.
=> fix(clippy): use first() instead of get(0)

docker/docker-compose.yml, docker/start-op-geth.sh, src/config/mod.rs, src/lib.rs, src/rpc/mod.rs, src/version/mod.rs
Per the RPC standard, there are several additional RPC endpoints that need to be supported beyond what Magi currently offers, including `version`, `rollupConfig`, and `syncStatus`. Furthermore, enhancements to `getOutputAtBlock` are necessary.
The present PR addresses the `version` and `rollupConfig` endpoints. Subsequent PRs will cover the remaining requirements. Note that I've already implemented `syncStatus` in a private fork and would move ASAP.
The RPC is important part as batcher uses RPC and by itself it's important to have full 
capability.
Also the PR contains fix for docker compose.
=> Feat: RPC support (part 1)

src/l1/mod.rs
- Only update finalized blocks if it has changed to avoid spamming the channel
=> Avoid duplicate FinalityUpdate in ChainWatcher

docker/start-op-geth.sh
The start-op-geth.sh has a repeat option of networkid.
It may cause some unexpected problem.
=> fix: op geth script

src/config/mod.rs
Need to update the unsafe_block_signer property value in the ChainConfig of Optimism Sepolia.
=> fix: unsafe block signer of op_sepolia

bin/magi.rs, src/config/mod.rs
This PR moves the match logic currently in ``bin/src/magi.rs`` to ``src/config/mod.rs``
Intended to streamline the binary code, and keep config related logic as close together as possible.
``ChainConfig::optimism`` and ``ChainConfig::from_network_name("optimism")`` are equivalent, and provides more flexibility if using a string for the network name is required for whatever reason.
=> chore: move ChainConfig match logic from bin -> config module

docs/architecture.md, src/engine/payload.rs, src/engine/traits.rs
Hello, 
I've found, that several links both in docs and code are pointing to outdated optimism specs, which [has moved](https://github.com/ethereum-optimism/optimism/blob/develop/specs/README.md) to [fresh repo](https://github.com/ethereum-optimism/specs). 
This PR updates the broken links to new repo. Updates are prepared for all occurrences without any code change.
@ncitron
=> 20240210 fix op links

src/l1/mod.rs
This field is actually never read, thus, another solution could be just removing the field.
=> Fixed `finalized` field calculation

src/network/service/discovery.rs
Added the base network's ENR address, which makes it easier to access the optimism sepolia network's unsafe payload messages.
=> add base network bootnodes

Cargo.lock, Cargo.toml, src/common/attributes_deposited.rs, src/common/mod.rs, src/config/mod.rs, src/derive/stages/attributes.rs, src/derive/stages/batches.rs, src/derive/state.rs, src/driver/engine_driver.rs, src/driver/info.rs, src/driver/mod.rs, src/driver/types.rs, src/engine/payload.rs, src/l1/chain_watcher.rs, src/rpc/mod.rs, src/runner/mod.rs
Migrates more types in the config module to alloy and updates a bunch of references to these variables.
=> chore(config): Migrate more types to Alloy

src/network/service/discovery.rs, src/network/service/enr.rs, src/network/service/mod.rs, src/network/service/types.rs
Ports `network` module types to alloy.
**Metadata**
Fixes #234
=> chore(network): Port Types to Alloy

src/derive/mod.rs, src/derive/stages/attributes.rs, src/derive/state.rs, src/l1/blob_encoding.rs, src/l1/chain_watcher.rs, src/l1/config_updates.rs, src/l1/l1_info.rs
Migrates the `l1` module to Alloy.
Two main concerns with this pr as it stands. Currently removed retrying from the l1 chain watcher provider since the `RetryClient` previously used is from `ethers` and I'm not seeing a good alternative. It also seems that the `reqwest::ClientBuilder` [does not offer a retry policy](https://github.com/seanmonstar/reqwest/issues/316).
The second concern is that the rpc `Log` type returned from the alloy provider does not hydrate the block information needed to construct the user deposit information. As in, it is missing the `l1 block number`, `l1 block hash`, and `log index` (within the block). As a work around, I've modified the log fetching to query each block's log set at a time so we can hydrate this information ourselves (assuming logs …
=> chore(l1): Migrate to Alloy

README.md, docker/.env.default, docker/README.md, docker/start-op-challenger.sh, docker/start-op-erigon.sh, docker/start-op-geth.sh, docs/architecture.md, src/config/mod.rs, src/derive/mod.rs, src/derive/stages/channels.rs, src/driver/mod.rs, src/l1/chain_watcher.rs, src/version/mod.rs
- Removed all references to `goerli` networks, as they have been deprecated in February. 🫡 
- Updated infra scripts and documentation references as well.
=> chore: remove deprecated networks: optimism-goerli and base-goerli

src/engine/auth.rs
Closes https://github.com/a16z/magi/issues/245
The problem is that if the jwt secret starts with `0x` - and most clients generate the jwt secret with `0x` prefix - the length is `66` instead of `64` so it panics.
To solve it, I simply remove the prefix if it exists
=> fix: handle 0x prefix to jwt secret if it exists

Cargo.lock, Cargo.toml, src/config/mod.rs, src/derive/mod.rs, src/derive/stages/attributes.rs, src/derive/stages/batcher_transactions.rs, src/derive/stages/batches.rs, src/derive/stages/block_input.rs, src/derive/stages/channels.rs, src/derive/stages/mod.rs, src/derive/stages/single_batch.rs, src/derive/stages/span_batch.rs, src/driver/mod.rs, src/engine/api.rs, src/engine/auth.rs, src/engine/payload.rs, src/l1/chain_watcher.rs, src/network/handlers/block_handler.rs, src/network/service/discovery.rs, src/network/service/types.rs, src/rpc/mod.rs, src/telemetry/logging.rs
Ports the config module to use `alloy-primitives` types instead of `ethers` types.
This is part 1 of the great alloy migration.
=> chore(config): Port to Alloy
